name: pivo_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.6.0
  auto_route: ^9.2.2
  elementary: ^3.2.0
  freezed_annotation: ^2.4.4
  flutter_masked_text2: ^0.9.1
  flutter_osm_plugin: ^1.3.5
  yandex_mapkit: ^4.1.0
  rxdart: ^0.28.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  dadata_suggestions:
    git:
      url: https://github.com/AurelVU/dadata_suggestions.git
      ref: null_saffety
  json_annotation: ^4.9.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  easy_debounce: ^2.0.3
  pointer_interceptor: ^0.10.1+2
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
  #   - images/a_dot_ham.jpeg
