name: pivo_front
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_localizations:
    sdk: flutter
  intl: any
  firebase_core: ^3.6.0
  auto_route: ^9.2.2
  elementary: ^3.2.0
  freezed_annotation: ^2.4.4
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/pivo1.webp
  #   - images/a_dot_ham.jpeg
