// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA17DktgF3BChQEebVR-GX60lg8_xui5I',
    appId: '1:305370310235:web:903d553a0da403928fc17e',
    messagingSenderId: '305370310235',
    projectId: 'pivo-b21a0',
    authDomain: 'pivo-b21a0.firebaseapp.com',
    storageBucket: 'pivo-b21a0.firebasestorage.app',
    measurementId: 'G-JWJVZ5957X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx6_lHc4Bs3n_F6SzSrvg4MKlV0ed-taw',
    appId: '1:305370310235:android:056fe1c3f8747e6c8fc17e',
    messagingSenderId: '305370310235',
    projectId: 'pivo-b21a0',
    storageBucket: 'pivo-b21a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlgzdWzNjOdRxDIeknRb7q1ayQcNJ0iOo',
    appId: '1:305370310235:ios:6f3f916efdcfbd3b8fc17e',
    messagingSenderId: '305370310235',
    projectId: 'pivo-b21a0',
    storageBucket: 'pivo-b21a0.firebasestorage.app',
    iosBundleId: 'com.itmo.pivo.app.pivoFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlgzdWzNjOdRxDIeknRb7q1ayQcNJ0iOo',
    appId: '1:305370310235:ios:6f3f916efdcfbd3b8fc17e',
    messagingSenderId: '305370310235',
    projectId: 'pivo-b21a0',
    storageBucket: 'pivo-b21a0.firebasestorage.app',
    iosBundleId: 'com.itmo.pivo.app.pivoFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA17DktgF3BChQEebVR-GX60lg8_xui5I',
    appId: '1:305370310235:web:1d0ece2c0f84cd728fc17e',
    messagingSenderId: '305370310235',
    projectId: 'pivo-b21a0',
    authDomain: 'pivo-b21a0.firebaseapp.com',
    storageBucket: 'pivo-b21a0.firebasestorage.app',
    measurementId: 'G-ZRC1HR21VX',
  );
}
